"""PAUS Robot perception core public exports."""

from .config import load_config
from .calibration import CameraCalibration, CalibrationResult, calibrate_camera_from_directory, load_camera_calibration, save_camera_calibration
from .detection import (
    MarkerDetection,
    PipelineResult,
    detect_marker,
    export_debug_images,
    render_visualization,
    result_to_dict,
    save_result_json,
)
from .pipeline import (
    SUPPORTED_IMAGE_EXTENSIONS,
    build_summary_record,
    make_output_subdir_name,
    process_image_array,
    process_image_file,
    write_summary_csv,
    write_summary_json,
)
from .bridge_protocol import pack_frame_packet, recv_frame_packet
from .sdk_camera import (
    DiscoveredCamera,
    capture_rgb_frame,
    discover_cameras,
    encode_bgr_frame_to_jpeg,
    export_factory_calibration_to_yaml,
    open_camera_runtime,
    read_runtime_calibration,
    resolve_camera_index,
    save_runtime_calibration_to_yaml,
)
from .pose import ApproachPlan, MarkerPose, build_approach_plan, estimate_marker_pose
from .transforms import (
    CalibrationResidualSummary,
    EyeToHandCalibrationSolution,
    Transform3D,
    average_transform_matrices,
    build_ax_xb_motion_pairs,
    evaluate_eye_to_hand_residuals,
    invert_transform_matrix,
    load_eye_to_hand_solution,
    make_transform_matrix,
    make_transform_struct,
    quaternion_xyzw_to_rotation_matrix,
    rotation_matrix_to_quaternion_xyzw,
    rotation_matrix_to_rpy_deg,
    rpy_deg_to_rotation_matrix,
    save_eye_to_hand_solution,
    solve_eye_to_hand_joint_absolute,
    solve_eye_to_hand_opencv_handeye,
    solve_ax_xb_hand_eye_park,
    split_transform_matrix,
)

__all__ = [
    "ApproachPlan",
    "CalibrationResult",
    "CalibrationResidualSummary",
    "CameraCalibration",
    "EyeToHandCalibrationSolution",
    "MarkerDetection",
    "MarkerPose",
    "PipelineResult",
    "DiscoveredCamera",
    "SUPPORTED_IMAGE_EXTENSIONS",
    "Transform3D",
    "average_transform_matrices",
    "build_ax_xb_motion_pairs",
    "build_approach_plan",
    "build_summary_record",
    "calibrate_camera_from_directory",
    "capture_rgb_frame",
    "detect_marker",
    "discover_cameras",
    "encode_bgr_frame_to_jpeg",
    "estimate_marker_pose",
    "evaluate_eye_to_hand_residuals",
    "export_factory_calibration_to_yaml",
    "export_debug_images",
    "load_camera_calibration",
    "load_eye_to_hand_solution",
    "load_config",
    "make_output_subdir_name",
    "make_transform_matrix",
    "make_transform_struct",
    "open_camera_runtime",
    "pack_frame_packet",
    "process_image_array",
    "process_image_file",
    "quaternion_xyzw_to_rotation_matrix",
    "read_runtime_calibration",
    "recv_frame_packet",
    "resolve_camera_index",
    "render_visualization",
    "result_to_dict",
    "rotation_matrix_to_quaternion_xyzw",
    "rotation_matrix_to_rpy_deg",
    "rpy_deg_to_rotation_matrix",
    "save_camera_calibration",
    "save_eye_to_hand_solution",
    "save_result_json",
    "save_runtime_calibration_to_yaml",
    "solve_eye_to_hand_joint_absolute",
    "solve_eye_to_hand_opencv_handeye",
    "solve_ax_xb_hand_eye_park",
    "split_transform_matrix",
    "write_summary_csv",
    "write_summary_json",
]
